In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import Imputer

wine_testing=pd.read_csv('C:\\Users\\assharma\\Downloads\\winequality-red.csv')
wine_testing

,Dummy,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,Ph,sulphates,alcohol,quality
0,Wine,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,Wine,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,Wine,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,Wine,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,Wine,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,Wine,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,Wine,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,Wine,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,Wine,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,Wine,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [2]:
wine_testing.columns=map(str.upper,wine_testing.columns)
wine_testing['DUMMY']=wine_testing['DUMMY'].str.upper()
wine_testing.rename(columns={'FREE SULFUR DIOXIDE':'FRF_SULF_DIX','TOTAL SULFUR DIOXIDE':'TOT_SULF_DIX'},inplace=True)

wine_testing

,DUMMY,FIXED ACIDITY,VOLATILE ACIDITY,CITRIC ACID,RESIDUAL SUGAR,CHLORIDES,FRF_SULF_DIX,TOT_SULF_DIX,DENSITY,PH,SULPHATES,ALCOHOL,QUALITY
0,WINE,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,WINE,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,WINE,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,WINE,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,WINE,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,WINE,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,WINE,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,WINE,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,WINE,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,WINE,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [3]:
wine_testing.drop(['DUMMY'],axis=1)

,FIXED ACIDITY,VOLATILE ACIDITY,CITRIC ACID,RESIDUAL SUGAR,CHLORIDES,FRF_SULF_DIX,TOT_SULF_DIX,DENSITY,PH,SULPHATES,ALCOHOL,QUALITY
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [4]:
wine_testing[wine_testing.isnull().values]

,DUMMY,FIXED ACIDITY,VOLATILE ACIDITY,CITRIC ACID,RESIDUAL SUGAR,CHLORIDES,FRF_SULF_DIX,TOT_SULF_DIX,DENSITY,PH,SULPHATES,ALCOHOL,QUALITY
6,WINE,7.9,0.60,NaN,1.6,0.069,15.0,59.0,NaN,3.30,0.46,9.4,5
6,WINE,7.9,0.60,NaN,1.6,0.069,15.0,59.0,NaN,3.30,0.46,9.4,5
7,WINE,7.3,0.65,0.00,1.2,0.065,15.0,21.0,NaN,3.39,NaN,10.0,7
7,WINE,7.3,0.65,0.00,1.2,0.065,15.0,21.0,NaN,3.39,NaN,10.0,7
9,WINE,7.5,0.50,0.36,6.1,0.071,17.0,102.0,NaN,3.35,0.80,10.5,5
10,WINE,6.7,0.58,0.08,1.8,0.097,15.0,65.0,NaN,3.28,0.54,9.2,5
11,WINE,7.5,0.50,0.36,6.1,0.071,17.0,102.0,NaN,3.35,0.80,10.5,5
15,WINE,8.9,0.62,0.19,3.9,NaN,51.0,148.0,0.9986,3.17,0.93,9.2,5
19,WINE,7.9,NaN,0.51,1.8,0.341,17.0,56.0,0.9969,3.04,1.08,9.2,6
112,WINE,8.4,0.60,0.10,2.2,NaN,14.0,111.0,0.9964,3.15,0.66,9.8,5
113,WINE,10.1,0.31,0.44,2.3,NaN,22.0,46.0,0.9988,3.32,0.67,9.7,6
114,WINE,7.8,0.56,0.19,1.8,NaN,12.0,47.0,0.9964,3.19,0.93,9.5,5
115,WINE,9.4,0.40,0.31,2.2,NaN,13.0,62.0,0.9966,3.07,0.63,10.5,6
116,WINE,8.3,0.54,0.28,1.9,NaN,11.0,40.0,0.9978,3.39,0.61,10.0,6
117,WINE,7.8,0.56,0.12,2.0,NaN,7.0,28.0,0.9970,3.37,0.50,9.4,6

In [5]:
wine_testing_imputed=wine_testing
imp = Imputer(missing_values='NaN',strategy='mean',axis=0)

C:\Users\assharma\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [6]:
wine_testing_imputed

,DUMMY,FIXED ACIDITY,VOLATILE ACIDITY,CITRIC ACID,RESIDUAL SUGAR,CHLORIDES,FRF_SULF_DIX,TOT_SULF_DIX,DENSITY,PH,SULPHATES,ALCOHOL,QUALITY
0,WINE,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,WINE,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,WINE,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,WINE,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,WINE,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,WINE,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,WINE,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,WINE,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,WINE,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,WINE,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [7]:
imp.fit(wine_testing_imputed.drop(['DUMMY'],axis=1))

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)

In [8]:
wine_testing_imputed= imp.transform(wine_testing_imputed.drop(['DUMMY'],axis=1))

In [9]:
wine_testing_imputed_PD=pd.DataFrame(wine_testing_imputed)

In [10]:
wine_testing_imputed_PD[wine_testing_imputed_PD.isnull().values]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Index: []